name       : python-pyjwt
version    : 2.6.0
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/P/PyJWT/PyJWT-2.6.0.tar.gz : 69285c7e31fc44f68a1feb309e948e0df53259d579295e6cfe2b1792329f05fd
homepage   : https://github.com/jpadilla/pyjwt
license    : MIT
component  : programming.python
summary    : JSON Web Token implementation in Python
description: |
    PyJWT is a Python library which allows you to encode and decode JSON Web Tokens (JWT). JWT is an open, industry-standard (RFC 7519) for representing claims securely between two parties.
builddeps  :
    - python-cryptography
    - python-pytest-cov
    - pytest-runner
rundeps    :
    - python-cryptography
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
