name       : python-pyjwt
version    : 2.7.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/P/PyJWT/PyJWT-2.7.0.tar.gz : bd6ca4a3c4285c1a2d4349e5a035fdf8fb94e04ccd0fcbe6ba289dae9cc3e074
homepage   : https://github.com/jpadilla/pyjwt
license    : MIT
component  : programming.python
summary    : JSON Web Token implementation in Python
description: |
    PyJWT is a Python library which allows you to encode and decode JSON Web Tokens (JWT). JWT is an open, industry-standard (RFC 7519) for representing claims securely between two parties.
builddeps  :
    - python-cryptography
    - python-pytest-cov
    - pytest-runner
rundeps    :
    - python-cryptography
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
