name       : python-pyjwt
version    : 2.3.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/P/PyJWT/PyJWT-2.3.0.tar.gz : b888b4d56f06f6dcd777210c334e69c737be74755d3e5e9ee3fe67dc18a0ee41
homepage   : https://github.com/jpadilla/pyjwt
license    : MIT
component  : programming.python
summary    : JSON Web Token implementation in Python
description: |
    PyJWT is a Python library which allows you to encode and decode JSON Web Tokens (JWT). JWT is an open, industry-standard (RFC 7519) for representing claims securely between two parties.
builddeps  :
    - python-cryptography
    - python-pytest-cov
    - pytest-runner
rundeps    :
    - python-cryptography
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
