name       : python-pyjwt
version    : 1.7.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/2f/38/ff37a24c0243c5f45f5798bd120c0f873eeed073994133c084e1cf13b95c/PyJWT-1.7.1.tar.gz : 8d59a976fb773f3e6a39c85636357c4f0e242707394cadadd9814f5cbaa20e96
license    : MIT
component  : programming.python
summary    : JSON Web Token implementation in Python
description: |
    `PyJWT` is a Python library which allows you to encode and decode JSON Web Tokens (JWT). JWT is an open, industry-standard (RFC 7519) for representing claims securely between two parties.
builddeps  :
    - python-pytest-cov
    - pytest-runner
    - python-setuptools
rundeps    :
    - python-cryptography
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test py.test -k 'not test_decode_no_algorithms_verify_false and not test_decode_no_algorithms_verify_signature_false'
#    %python3_test py.test3 -k 'not test_decode_no_algorithms_verify_false and not test_decode_no_algorithms_verify_signature_false'
