name       : python-pyjwt
version    : 2.1.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/P/PyJWT/PyJWT-2.1.0.tar.gz : fba44e7898bbca160a2b2b501f492824fc8382485d3a6f11ba5d0c1937ce6130
homepage   : https://github.com/jpadilla/pyjwt
license    : MIT
component  : programming.python
summary    : JSON Web Token implementation in Python
description: |
    PyJWT is a Python library which allows you to encode and decode JSON Web Tokens (JWT). JWT is an open, industry-standard (RFC 7519) for representing claims securely between two parties.
builddeps  :
    - python-cryptography
    - python-pytest-cov
    - pytest-runner
rundeps    :
    - python-cryptography
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
